version: '2.3'

# TODO: [zodac] Extract sensitive data to an env file, allow deployment to override with 'real' values
services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    hostname: frontend
    depends_on:
      - wildfly
    links:
      - wildfly
    networks:
      - prod
    ports:
      - 85:80

  builder_java:
    build:
      context: .
      dockerfile: docker/builder/java/Dockerfile
    container_name: builder_java
    hostname: builder_java
    networks:
      - prod
    volumes:
      - /opt/jboss/wildfly/standalone/deployments/

  wildfly:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
    container_name: wildfly
    hostname: wildfly
    depends_on:
      - builder_java
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # Stats parsing configuration
      STATS_URL_ROOT: "https://api2.foldingathome.org"
      # NOTE: The monthly reset will always occur at 00:55 on the first of the month
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "15"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      # Database configuration
      DEPLOYED_DATABASE: "postgres"
      JDBC_CONNECTION_URL: "jdbc:postgresql://postgres:5432/folding_db"
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - builder_java
      - postgres
    networks:
      - prod
    ports:
      - 8080:8080
      - 9990:9990
    volumes:
      - wildfly_logs:/opt/jboss/wildfly/standalone/log
    volumes_from:
      - builder_java

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres
    hostname: postgres
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "folding_user"
      POSTGRES_PASSWORD: "shroot"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "folding_user"
      PGPASSWORD: "shroot"
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    networks:
      - prod
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # Volume to save the PostgreSQL contents
  # TODO: [zodac] Should we also set up a cron job on server to dump the DB every month? Talk to Axi
  postgres_data:
  # Volume to save the Wildfly logs in case of a crash
  wildfly_logs:

networks:
  prod: