services:

  frontend_dev:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # Docker image versions
        NODE_VERSION: "18.8"
        # Build arguments
        ADMIN_EMAIL_ADDRESS: "email@test.com"
        FORUM_LINK: "https://forums.extremehw.net/forum/125-extreme-team-folding"
        HTTPS_FRONTEND_PORT: "80"
        REST_ENDPOINT_URL: "http://127.0.0.1:8081/folding"
        ROOT_URL: "http://127.0.0.1:81/"
        TITLE: "Extreme Team Folding"
        UPDATE_ENABLED: "false"
    container_name: frontend_dev
    hostname: frontend_dev
    depends_on:
      - backend_dev
    links:
      - backend_dev
    networks:
      - development
    ports:
      - "81:80"
    volumes_from:
      - backend_dev

  backend_dev:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        # Docker image versions
        DEBIAN_VERSION: "11.4"
        JAVA_VERSION: "18"
        MAVEN_VERSION: "3.8.6"
        # Build arguments
        KEYSTORE_PASSWORD: "shroot"
        NEXUS_URL: "${NEXUS_URL}"
    container_name: backend_dev
    hostname: backend-dev # Using a dash as Java's URI builder will fail with an underscore
    environment:
      # External URL configuration
      LARS_URL_ROOT: "http://backend-dev:8081/folding"
      STATS_URL_ROOT: "http://backend-dev:8081/folding"
      REDIRECT_URL: "http://127.0.0.1:81/"
      # Spring configuration
      DEPLOYMENT_TYPE: "test"
      MULTIPLE_LOG_FILES: "false"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57:00 on the last day of the month
      ENABLE_LARS_HARDWARE_UPDATE: "false"
      ENABLE_MONTHLY_RESULT_STORAGE: "false"
      ENABLE_STATS_MONTHLY_RESET: "false"
      # Stats parsing configuration
      ENABLE_STATS_SCHEDULED_PARSING: "false"
      SECONDS_BETWEEN_HTTP_REQUEST_ATTEMPTS: "0"
      MAXIMUM_HTTP_REQUEST_ATTEMPTS: "3"
      # Category configuration
      USERS_IN_AMD_GPU: "1"
      USERS_IN_NVIDIA_GPU: "1"
      USERS_IN_WILDCARD: "1"
      # Database configuration
      DEPLOYED_DATABASE: "postgresql"
      JDBC_CONNECTION_URL: "jdbc:postgresql://database_dev:5432/folding_db"
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
      # Swagger documentation
      CONTACT_NAME: "zodac"
      FORUM_LINK: "https://forums.extremehw.net/forum/125-extreme-team-folding"
      REST_ENDPOINT_URL: "http://127.0.0.1:8081/folding"
    links:
      - database_dev
    networks:
      - development
    ports:
      - "8081:8081"
    volumes:
      - /usr/local/certs/stats/

  database_dev:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
      args:
        # Docker image versions
        POSTGRES_VERSION: "14.5"
        # Build arguments
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
        READ_ONLY_USERNAME: "root2"
        READ_ONLY_PASSWORD: "shroot2"
        POSTGRES_USER: "folding_user"
    container_name: database_dev
    hostname: database_dev
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "folding_user"
      POSTGRES_PASSWORD: "shroot"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "folding_user"
      PGPASSWORD: "shroot"
    networks:
      - development
    ports:
      - "5433:5432"

  selenium_chrome:
    image: selenium/standalone-chrome:104.0
    container_name: selenium_chrome
    hostname: selenium_chrome
    depends_on:
      - frontend_dev
    links:
      - frontend_dev
    ports:
      - "4444:4444"
    networks:
      - development

  selenium_edge:
    image: selenium/standalone-edge:104.0
    container_name: selenium_edge
    hostname: selenium_edge
    depends_on:
      - frontend_dev
    links:
      - frontend_dev
    ports:
      - "4445:4444"
    networks:
      - development

  selenium_firefox:
    image: selenium/standalone-firefox:103.0
    container_name: selenium_firefox
    hostname: selenium_firefox
    depends_on:
      - frontend_dev
    links:
      - frontend_dev
    ports:
      - "4446:4444"
    networks:
      - development

networks:
  development:
