version: '2.3'

services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        ROOT_URL: "https://internal-secure.axihub.ca/folding"
    container_name: frontend
    hostname: frontend
    depends_on:
      - wildfly
    links:
      - wildfly
    networks:
      - production
    ports:
      - "85:80"

  wildfly:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "${BACKEND_USER}"
        ADMIN_PASSWORD: "${BACKEND_PASSWORD}"
        DEPLOYMENT_TYPE: "production"
    container_name: wildfly
    hostname: wildfly
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # Stats parsing configuration
      STATS_URL_ROOT: "https://api2.foldingathome.org"
      LARS_URL_ROOT: "https://folding.lar.systems/"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57 on the last day of the month
      ENABLE_STATS_MONTHLY_RESET: "true"
      ENABLE_MONTHLY_RESULT_STORAGE: "true"
      ENABLE_LARS_HARDWARE_UPDATE: "true"
      # Scheduled stats parsing configuration
      # NOTE: This time is hardcoded in the frontend, will also need to update 'timer.js'
      ENABLE_STATS_SCHEDULED_PARSING: "true"
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "55"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      STATS_PARSING_SCHEDULE_FIRST_DAY_OF_MONTH: "3"
      STATS_PARSING_SCHEDULE_LAST_DAY_OF_MONTH: "31"
      # Database configuration
      DEPLOYED_DATABASE: "postgresql"
      JDBC_CONNECTION_URL: "jdbc:postgresql://postgres:5432/folding_db"
      JDBC_CONNECTION_USER: "${DB_USER}"
      JDBC_CONNECTION_PASSWORD: "${DB_PASSWORD}"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - postgres
    networks:
      - production
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
    volumes:
      - wildfly_logs:/opt/jboss/wildfly/standalone/log

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        ADMIN_USERNAME: "${ADMIN_USER}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
        READ_ONLY_USERNAME: "${READ_ONLY_USER}"
        READ_ONLY_PASSWORD: "${READ_ONLY_PASSWORD}"
    container_name: postgres
    hostname: postgres
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "${DB_USER}"
      PGPASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    networks:
      - production
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  production:

volumes:
  # Volume to save maven .m2 for subsequent builds
  m2:
  # Volume to save the PostgreSQL contents
  postgres_data:
  # Volume to save the Wildfly logs in case of a crash
  wildfly_logs:
