version: '2.3'

services:

  frontend_dev:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        ROOT_URL: "http://127.0.0.1:8081/folding"
        UPDATE_MINUTE: "55"
    container_name: frontend_dev
    hostname: frontend_dev
    depends_on:
      - backend_dev
    links:
      - backend_dev
    networks:
      - development
    ports:
      - "81:80"
    volumes:
      - "${SSL_CERT_DIRECTORY}:/usr/local/apache2/conf/certs"

  backend_dev:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
        DEPLOYMENT_TYPE: "test"
    container_name: backend_dev
    hostname: backend-dev # Using a dash as Java's URI builder will fail with an underscore
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # External URL configuration
      STATS_URL_ROOT: "http://backend-dev:8080"
      LARS_URL_ROOT: "http://backend-dev:8080"
      TC_HOMEPAGE_URL: "http://frontend_dev/"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57 on the last day of the month
      ENABLE_STATS_MONTHLY_RESET: "false"
      ENABLE_MONTHLY_RESULT_STORAGE: "false"
      ENABLE_LARS_HARDWARE_UPDATE: "false"
      # Scheduled stats parsing configuration
      ENABLE_STATS_SCHEDULED_PARSING: "false"
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "55"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      # Database configuration
      DEPLOYED_DATABASE: "postgresql"
      JDBC_CONNECTION_URL: "jdbc:postgresql://database_dev:5432/folding_db"
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - database_dev
    networks:
      - development
    ports:
      # For test env, we expose the HTTP endpoint, not HTTPS
      - "8081:8080"
      - "9991:9990"

  database_dev:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
        READ_ONLY_USERNAME: "root2"
        READ_ONLY_PASSWORD: "shroot2"
    container_name: database_dev
    hostname: database_dev
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "folding_user"
      POSTGRES_PASSWORD: "shroot"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "folding_user"
      PGPASSWORD: "shroot"
    networks:
      - development
    ports:
      - "5433:5432"

networks:
  development:
