version: '2.3'

# TODO: [zodac] Extract sensitive data to an env file, allow deployment to override with 'real' values
services:

  builder_java:
    build:
      context: .
      dockerfile: docker/builder/java/Dockerfile
    container_name: builder_java
    hostname: builder_java
    volumes:
      - /opt/jboss/wildfly/standalone/deployments/

  wildfly:
    build: ./docker/wildfly
    container_name: wildfly
    hostname: wildfly
    depends_on:
      - builder_java
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # Database configuration
      JDBC_CONNECTION_URL: "jdbc:postgresql://postgres:5432/folding_db"
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - builder_java
      - postgres
    ports:
      - 8080:8080
      - 8787:8787
      - 9990:9990
      - 9999:9999
    volumes:
      - wildfly_logs:/opt/jboss/wildfly/standalone/log
    volumes_from:
      - builder_java

  postgres:
    build: ./docker/postgres
    container_name: postgres
    hostname: postgres
    environment:
      # First 4 variables used to configure DB
      - POSTGRES_DB=folding_db
      - POSTGRES_USER=folding_user
      - POSTGRES_PASSWORD=shroot
      - POSTGRES_PORT=5432
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      - PGDATABASE=folding_db
      - PGUSER=folding_user
      - PGPASSWORD=shroot
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  # Volume to save the PostgreSQL contents
  # TODO: [zodac] Should we also set up a cron job on server to dump the DB every month? Talk to Axi
  postgres_data:
  # Volume to save the Wildfly logs in case of a crash
  wildfly_logs:
