version: '2.3'

networks:
  production:

services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # Docker image versions
        NODE_VERSION: "22.3.0" # https://hub.docker.com/_/node
        # Build arguments
        ADMIN_EMAIL_ADDRESS: "${ADMIN_EMAIL_ADDRESS}"
        FORUM_LINK: "${FORUM_LINK}"
        HTTPS_FRONTEND_PORT: "${HTTPS_FRONTEND_PORT}"
        REST_ENDPOINT_URL: "${REST_ENDPOINT_URL}"
        ROOT_URL: "${ROOT_URL}"
        TITLE: "${TITLE}"
        UPDATE_ENABLED: "${STATS_ENABLED}"
    container_name: frontend
    hostname: frontend
    depends_on:
      - backend
    networks:
      - production
    ports:
      - "${HTTPS_FRONTEND_PORT}:${HTTPS_FRONTEND_PORT}"
    restart: unless-stopped
    volumes_from:
      - backend:ro

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        # Docker image versions
        DEBIAN_VERSION: "12.5"    # https://hub.docker.com/_/debian
        JAVA_VERSION: "22.0.1_8"  # https://hub.docker.com/_/eclipse-temurin
        MAVEN_VERSION: "3.9.7"    # https://hub.docker.com/_/maven
        # Build arguments
        KEYSTORE_PASSWORD: "${KEYSTORE_PASSWORD}"
    container_name: backend
    hostname: backend
    environment:
      # External URL configuration
      LARS_URL_ROOT: "${LARS_URL_ROOT}"
      STATS_URL_ROOT: "${STATS_URL_ROOT}"
      REDIRECT_URL: "${ROOT_URL}"
      # Spring configuration
      DEPLOYMENT_TYPE: "production"
      JVM_MAX: "1024m"
      JVM_MIN: "128m"
      MULTIPLE_LOG_FILES: "true"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57:00 on the last day of the month
      ENABLE_LARS_HARDWARE_UPDATE: "${ENABLE_LARS_HARDWARE_UPDATE}"
      ENABLE_MONTHLY_RESULT_STORAGE: "${ENABLE_MONTHLY_RESULT_STORAGE}"
      ENABLE_STATS_MONTHLY_RESET: "${ENABLE_STATS_MONTHLY_RESET}"
      # Stats parsing configuration
      # This value should match the value of 'UPDATE_ENABLED' in the 'frontend' container
      ENABLE_STATS_SCHEDULED_PARSING: "${STATS_ENABLED}"
      SECONDS_BETWEEN_HTTP_REQUEST_ATTEMPTS: "${SECONDS_BETWEEN_HTTP_REQUEST_ATTEMPTS}"
      MAXIMUM_HTTP_REQUEST_ATTEMPTS: "${MAXIMUM_HTTP_REQUEST_ATTEMPTS}"
      # Category configuration
      USERS_IN_AMD_GPU: "${USERS_IN_AMD_GPU}"
      USERS_IN_NVIDIA_GPU: "${USERS_IN_NVIDIA_GPU}"
      USERS_IN_WILDCARD: "${USERS_IN_WILDCARD}"
      # Spring configuration
      spring.datasource.url: "jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
      spring.datasource.driver: "org.postgresql.Driver"
      spring.datasource.username: "${DB_USER}"
      spring.datasource.password: "${DB_PASSWORD}"
      spring.datasource.database.type: "postgresql"
      server.ssl.key-store-password: "${KEYSTORE_PASSWORD}"
      # Swagger documentation
      CONTACT_NAME: "${CONTACT_NAME}"
      FORUM_LINK: "${FORUM_LINK}"
      REST_ENDPOINT_URL: "${REST_ENDPOINT_URL}"
    healthcheck:
      test: "curl --fail --silent -k https://localhost:8443/folding/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - production
    ports:
      - "${HTTPS_BACKEND_PORT}:${HTTPS_BACKEND_PORT}"
    restart: unless-stopped
    volumes:
      - backend_certs:/usr/local/certs/stats/
      - backend_logs:/var/backend/logs/

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
      args:
        # Docker image versions
        POSTGRES_VERSION: "16.3" # https://hub.docker.com/_/postgres
        # Build arguments
        ADMIN_USERNAME: "${ADMIN_USER}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
        READ_ONLY_USERNAME: "${READ_ONLY_USER}"
        READ_ONLY_PASSWORD: "${READ_ONLY_PASSWORD}"
        POSTGRES_USER: "${DB_USER}"
    container_name: database
    hostname: database
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "${POSTGRES_DB_NAME}"
      PGUSER: "${DB_USER}"
      PGPASSWORD: "${DB_PASSWORD}"
    networks:
      - production
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    volumes:
      - database_content:/var/lib/postgresql/data

volumes:
  # Volume to save the database contents
  database_content: { }
  # Volume to save the backend logs in case of a crash
  backend_logs: { }
  # Volume to save the generated SSL certs for the backend
  backend_certs: { }
