networks:
  production:
    name: production
    driver: bridge

services:

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # Docker image versions
        HTTPD_VERSION: "2.4.65"     # https://hub.docker.com/_/httpd/tags
        MINIFY_VERSION: "v2.24.3"   # https://hub.docker.com/r/tdewolff/minify/tags
        NODE_VERSION: "24.8.0"      # https://hub.docker.com/_/node/tags
        # Build arguments
        ADMIN_EMAIL_ADDRESS: "${ADMIN_EMAIL_ADDRESS}"
        FORUM_LINK: "${FORUM_LINK}"
        REST_ENDPOINT_URL: "${REST_ENDPOINT_URL}"
        ROOT_URL: "${ROOT_URL}"
        TITLE: "${TITLE}"
        UPDATE_ENABLED: "${STATS_ENABLED}"
    container_name: frontend
    hostname: frontend
    depends_on:
      - backend
    networks:
      - production
    ports:
      - "${HTTPS_FRONTEND_PORT}:443"
    restart: "unless-stopped"
    volumes_from:
      - backend:ro

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        # Docker image versions
        DEBIAN_VERSION: "12"      # https://console.cloud.google.com/artifacts/docker/distroless/us/gcr.io
        JAVA_VERSION: "25_36"     # https://hub.docker.com/_/eclipse-temurin/tags
        MAVEN_VERSION: "3.9.11"   # https://hub.docker.com/_/maven/tags
        # Build arguments
        KEYSTORE_PASSWORD: "${KEYSTORE_PASSWORD}"
    container_name: backend
    hostname: backend
    environment:
      # External URL configuration
      LARS_URL_ROOT: "${LARS_URL_ROOT}"
      STATS_URL_ROOT: "${STATS_URL_ROOT}"
      REDIRECT_URL: "${ROOT_URL}"
      # Spring configuration
      LOG_LEVEL: "INFO"
      DEPLOYMENT_TYPE: "production"
      JVM_MAX: "1024m"
      JVM_MIN: "128m"
      MULTIPLE_LOG_FILES: "true"
      SERVER_SSL_KEY_STORE_PASSWORD: "${KEYSTORE_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB_NAME}"
      SPRING_DATASOURCE_DRIVER: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_DATASOURCE_DATABASE_TYPE: "postgresql"
      # Application config
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57:00 on the last day of the month
      ENABLE_LARS_HARDWARE_UPDATE: "${ENABLE_LARS_HARDWARE_UPDATE}"
      ENABLE_MONTHLY_RESULT_STORAGE: "${ENABLE_MONTHLY_RESULT_STORAGE}"
      ENABLE_STATS_MONTHLY_RESET: "${ENABLE_STATS_MONTHLY_RESET}"
      # Stats parsing configuration
      MAXIMUM_HTTP_REQUEST_ATTEMPTS: "${MAXIMUM_HTTP_REQUEST_ATTEMPTS}"
      SECONDS_BETWEEN_HTTP_REQUEST_ATTEMPTS: "${SECONDS_BETWEEN_HTTP_REQUEST_ATTEMPTS}"
      STATS_SCHEDULED_PARSING_ENABLED: "${STATS_ENABLED}"
      STATS_SCHEDULED_PARSING_CRON: "0 55 * 3-31 * *"
      # Category configuration
      USERS_IN_AMD_GPU: "${USERS_IN_AMD_GPU}"
      USERS_IN_NVIDIA_GPU: "${USERS_IN_NVIDIA_GPU}"
      USERS_IN_WILDCARD: "${USERS_IN_WILDCARD}"
      # Swagger documentation
      CONTACT_NAME: "${CONTACT_NAME}"
      FORUM_LINK: "${FORUM_LINK}"
      REST_ENDPOINT_URL: "${REST_ENDPOINT_URL}"
    networks:
      - production
    ports:
      - "${HTTPS_BACKEND_PORT}:8443"
    restart: "unless-stopped"
    volumes:
      - backend_certs:/usr/local/certs/stats/
      - backend_logs:/var/backend/logs/

  database:
    build:
      context: .
      dockerfile: docker/database/Dockerfile
      args:
        # Docker image versions
        POSTGRES_VERSION: "18.0" # https://hub.docker.com/_/postgres/
        # Build arguments
        ADMIN_USERNAME: "${ADMIN_USER}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
        READ_ONLY_USERNAME: "${READ_ONLY_USER}"
        READ_ONLY_PASSWORD: "${READ_ONLY_PASSWORD}"
        POSTGRES_USER: "${DB_USER}"
    container_name: database
    hostname: database
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      PGDATA: "/var/lib/postgresql/system/data"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "${POSTGRES_DB_NAME}"
      PGUSER: "${DB_USER}"
      PGPASSWORD: "${DB_PASSWORD}"
    networks:
      - production
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: "unless-stopped"
    volumes:
      - database_content:/var/lib/postgresql/data

volumes:
  # Volume to save the database contents
  database_content: { }
  # Volume to save the backend logs in case of a crash
  backend_logs: { }
  # Volume to save the generated SSL certs for the backend
  backend_certs: { }
