version: '2.3'

# TODO: [zodac] Extract sensitive data to an env file, allow deployment to override with 'real' values
services:

  builder_java_dev:
    build:
      context: .
      dockerfile: docker/builder_dev/java/Dockerfile
    container_name: builder_java_dev
    hostname: builder_java_dev
    networks:
      - dev
    volumes:
      - /opt/jboss/wildfly/standalone/deployments/

  wildfly_dev:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
    container_name: wildfly_dev
    hostname: wildfly_dev
    depends_on:
      - builder_java_dev
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # Stats parsing configuration
      STATS_URL_ROOT: "http://192.168.99.100:8081"
      # NOTE: The monthly reset will always occur at 00:55 on the first of the month
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "15"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      # Database configuration
      DEPLOYED_DATABASE: "postgres"
      JDBC_CONNECTION_URL: "jdbc:postgresql://192.168.99.100:5433/folding_db" # TODO: [zodac] Not working with 'postgres_dev' as host
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - builder_java_dev
      - postgres_dev
    networks:
      - dev
    ports:
      - 8081:8080
      - 9991:9990
    volumes_from:
      - builder_java_dev

  postgres_dev:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres_dev
    hostname: postgres_dev
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "folding_user"
      POSTGRES_PASSWORD: "shroot"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "folding_user"
      PGPASSWORD: "shroot"
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    networks:
      - dev
    ports:
      - 5433:5432
    restart: always

networks:
  dev:
