version: '2.3'

services:

  frontend_dev:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend_dev
    hostname: frontend_dev
    depends_on:
      - wildfly_dev
    links:
      - wildfly_dev
    networks:
      - development
    ports:
      - "86:80"

  wildfly_dev:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
        DEPLOYMENT_TYPE: "test"
    container_name: wildfly_dev
    hostname: wildfly-dev # Using a dash as Java's URI builder will fail with an underscore
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # Stats parsing configuration
      STATS_URL_ROOT: "http://wildfly-dev:8080"
      LARS_URL_ROOT: "http://wildfly-dev:8080"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57 on the last day of the month
      ENABLE_STATS_MONTHLY_RESET: "false"
      ENABLE_MONTHLY_RESULT_STORAGE: "false"
      ENABLE_LARS_HARDWARE_UPDATE: "false"
      # Scheduled stats parsing configuration
      ENABLE_STATS_SCHEDULED_PARSING: "false"
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "55"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      # Database configuration
      DEPLOYED_DATABASE: "postgresql"
      JDBC_CONNECTION_URL: "jdbc:postgresql://postgres_dev:5432/folding_db"
      JDBC_CONNECTION_USER: "folding_user"
      JDBC_CONNECTION_PASSWORD: "shroot"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    links:
      - postgres_dev
    networks:
      - development
    ports:
      - "8081:8080"
      - "9991:9990"

  postgres_dev:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        ADMIN_USERNAME: "root"
        ADMIN_PASSWORD: "shroot"
        READ_ONLY_USERNAME: "root2"
        READ_ONLY_PASSWORD: "shroot2"
    container_name: postgres_dev
    hostname: postgres_dev
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "folding_user"
      POSTGRES_PASSWORD: "shroot"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "folding_user"
      PGPASSWORD: "shroot"
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    networks:
      - development
    ports:
      - "5433:5432"
    restart: always

networks:
  development:
