version: '2.3'

services:

  frontend:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        ROOT_URL: "https://internal.axihub.ca/folding"
        SSL_CERT_DIRECTORY: "${SSL_CERT_DIRECTORY}"
    container_name: frontend
    hostname: frontend
    depends_on:
      - backend
    links:
      - backend
    networks:
      - production
    ports:
      - "443:443"
    volumes:
      - "${SSL_CERT_DIRECTORY}:/usr/local/apache2/conf/certs"

  backend:
    build:
      context: .
      dockerfile: docker/wildfly/Dockerfile
      args:
        ADMIN_USERNAME: "${BACKEND_USER}"
        ADMIN_PASSWORD: "${BACKEND_PASSWORD}"
        DEPLOYMENT_TYPE: "production"
    container_name: backend
    hostname: backend
    environment:
      # Container configuration
      JAVA_OPTS: -Xms512m -Xmx2g -Djava.net.preferIPv4Stack=true
      # External URL configuration
      STATS_URL_ROOT: "https://api2.foldingathome.org"
      LARS_URL_ROOT: "https://folding.lar.systems/"
      TC_HOMEPAGE_URL: "http://teamcomp.axihub.ca/"
      # NOTE: The monthly reset, result storage and LARS update will always occur at 23:57 on the last day of the month
      ENABLE_STATS_MONTHLY_RESET: "true"
      ENABLE_MONTHLY_RESULT_STORAGE: "true"
      ENABLE_LARS_HARDWARE_UPDATE: "true"
      # Scheduled stats parsing configuration
      # TODO: This time is hardcoded in the UI, will also need to update 'timer.js'
      ENABLE_STATS_SCHEDULED_PARSING: "true"
      STATS_PARSING_SCHEDULE_HOUR: "*"
      STATS_PARSING_SCHEDULE_MINUTE: "55"
      STATS_PARSING_SCHEDULE_SECOND: "0"
      STATS_PARSING_SCHEDULE_FIRST_DAY_OF_MONTH: "3"
      STATS_PARSING_SCHEDULE_LAST_DAY_OF_MONTH: "31"
      # Database configuration
      DEPLOYED_DATABASE: "postgresql"
      JDBC_CONNECTION_URL: "jdbc:postgresql://database:5432/folding_db"
      JDBC_CONNECTION_USER: "${DB_USER}"
      JDBC_CONNECTION_PASSWORD: "${DB_PASSWORD}"
      JDBC_CONNECTION_DRIVER: "org.postgresql.Driver"
    healthcheck:
      test: curl -k --fail https://localhost:8443/folding || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    links:
      - database
    networks:
      - production
    ports:
      - "8443:8443"
      - "9990:9990"
    volumes:
      - backend_logs:/opt/jboss/wildfly/standalone/log

  database:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        ADMIN_USERNAME: "${ADMIN_USER}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
        READ_ONLY_USERNAME: "${READ_ONLY_USER}"
        READ_ONLY_PASSWORD: "${READ_ONLY_PASSWORD}"
    container_name: database
    hostname: database
    environment:
      # First 4 variables used to configure DB
      POSTGRES_DB: "folding_db"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: "5432"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      PGDATABASE: "folding_db"
      PGUSER: "${DB_USER}"
      PGPASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30
    networks:
      - production
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database_content:/var/lib/postgresql/data

networks:
  production:

volumes:
  # Volume to save the database contents
  database_content:
  # Volume to save the backend logs in case of a crash
  backend_logs:
