global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
    tls_config:
      insecure_skip_verify: true

  - job_name: 'spring-actuator'
    metrics_path: '/folding/actuator/prometheus/'
    scrape_interval: 60s
    scheme: https
    static_configs:
      - targets: [ 'backend:8443' ]
    tls_config:
      cert_file: /usr/local/certs/stats/folding-stats.crt
      key_file: /usr/local/certs/stats/folding-stats.key
      insecure_skip_verify: true
