global:
  scrape_interval: 60s
  evaluation_interval: 60s
  # scrape_timeout: 10s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time-series scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    scheme: https
    static_configs:
      - targets: [ 'HOST_IP:8443' ]