name: Java CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/doc.yml'
      - '.github/workflows/license_update.yml'
      - '.github/workflows/other.yml'
      - '.github/workflows/version_update.yml'
      - 'ci/doc/**'
      - 'ci/other/**'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
  schedule:
    # Run at 3:30 every Sunday to check for new CVEs
    - cron: '30 3 * * 0'

jobs:
  analyze:
    name: Java Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache local .m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache dependency-check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check/
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-

      - name: Set up maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-fetch-depth: 0
          java-distribution: 'temurin'
          java-version: '25'
          maven-version: '3.9.11'

      - name: Deploy docker containers
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: docker-compose-dev.yml

      - name: Run linters and unit/integration tests, then publish results to SonarQube
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONARQUBE_PAT: ${{ secrets.SONARQUBE_PAT }}
        run: mvn clean install -Dall -Dsonarqube
