name: Java CI

on:
  push:
    branches: [ master ]
  schedule:
    # Run once a week to check for new CVEs
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache local .m2
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          maven-version: '3.9.8'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        id: deploy
        run: docker-compose --file docker-compose-dev.yml up --build --detach

      - name: Run linters and unit tests (including SonarQube)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          SONARQUBE_PAT: ${{ secrets.SONARQUBE_PAT }}
        run: mvn clean install -Dall -Dsonarqube
        if: steps.deploy.outcome == 'success'

      - name: Shut down Docker Compose
        if: steps.deploy.outcome == 'success'
        run: docker-compose --file docker-compose-dev.yml down
