name: Java CI

on:
  push:
    branches: [ master ]
  schedule:
    # Run once a week to check for new CVEs
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '22'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: 'temurin'
          java-version: '22'
          maven-version: '3.9.8'
      - name: Cache local .m2
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**.pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run linters and unit tests (including SonarQube)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          SONARQUBE_PAT: ${{ secrets.SONARQUBE_PAT }}
        run: mvn clean install -Dlint -Dunit-tests -Dsonarqube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
