name: Java CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/dockerfile.yml'
      - '.github/workflows/javascript.yml'
      - 'ci/.hadolint.yaml'
      - 'CONTRIBUTING.md'
      - 'README.md'
  schedule:
    # Run once a week to check for new CVEs
    - cron: '0 0 * * 0'

jobs:
  analyze:
    name: Java Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Cache local .m2
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-distribution: 'temurin'
          java-version: '22'
          maven-version: '3.9.8'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy docker containers
        id: deploy
        run: docker compose --file docker-compose-dev.yml up --build --detach

      - name: Run linters and unit/integration tests, then publish results to SonarQube
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          SONARQUBE_PAT: ${{ secrets.SONARQUBE_PAT }}
        run: mvn clean install -Dall -Dsonarqube

      - name: Shut down docker containers
        run: docker compose --file docker-compose-dev.yml down
        if: steps.deploy.outcome == 'success'
