# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: Javascript CI

on: [push]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      # CodeQL Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.25.11
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.25.11

      # SonarQube Analysis
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.4.0'

      - name: Install dependencies
        run: npm install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=folding-stats-js  \
            -Dsonar.sources=docker/frontend/js \
            -Dsonar.host.url=https://sonarqube.zodac.me \
            -Dsonar.login=${{ secrets.SONARQUBE_PAT }}
