name: Java CI

on:
  push:
    branches: [ master ]
  schedule:
    # Run once a week to check for new CVEs
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.0.0
      - name: Set up JDK 21
        uses: actions/setup-java@v3.13.0
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-distribution: 'temurin'
          java-version: '21'
          maven-version: '3.9.4'
      - name: Cache local .m2
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**.pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run linters and unit tests
        run: mvn clean install -Dlint -Dunit-tests
