name: Java CI

on:
  push:
    branches: [ master ]
  schedule:
    # Run once a week to check for new CVEs
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '20'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          distribution: 'temurin'
          java-version: '20'
          maven-version: '3.9.3'
      - name: Cache local .m2
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**.pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run linters and unit tests
        run: mvn clean install -Dlint -Dunit-tests
