name: Other CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/other.yml'
      - 'docker/frontend/css/**'
      - 'docker/frontend/pages/**'

jobs:
  analyze:
    name: Other Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Git
        run: git config --global user.name 'github-actions' && git config --global user.email 'github-actions@github.com'

      - name: Initialize variable
        id: init_sources
        run: echo "SOURCES=" >> $GITHUB_ENV

      - name: Check if there are CSS changes
        id: check_css
        run: |
          echo "CSS diff:" && \
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.*/frontend/css/';
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.*/frontend/css/'; then
            echo "::set-output name=changed::true"
            echo "SOURCES=$SOURCES,/usr/src/docker/frontend/css/" >> $GITHUB_ENV
          else
            echo "::set-output name=changed::false"
          fi

      - name: Check if there are HTML changes
        id: check_html
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^.*/frontend/pages/'; then
            echo "::set-output name=changed::true"
            echo "SOURCES=$SOURCES,/usr/src/docker/frontend/pages/" >> $GITHUB_ENV
          else
            echo "::set-output name=changed::false"
          fi

        # SonarQube Analysis
      - name: Execute SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT }}
        run: |
          echo "Output: $SOURCES" && \
          docker run \
          --rm \
          -e SONAR_HOST_URL="https://sonarqube.zodac.me" \
          -v "$(pwd):/usr/src/" \
          sonarsource/sonar-scanner-cli:10.0 \
            -Dsonar.projectKey=folding-stats-other  \
            -Dsonar.sources="$SOURCES" \
            -Dsonar.token=${{ secrets.SONARQUBE_PAT }}
