name: Other CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/other.yml'
      - 'ci/.hadolint.yaml'
      - 'docker/backend/Dockerfile'
      - 'docker/database/Dockerfile'
      - 'docker/frontend/Dockerfile'
      - 'docker/frontend/css/**'
      - 'docker/frontend/js/**'
      - 'docker/frontend/pages/**'

jobs:
  analyze:
    name: Other Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      # Additional CSS Analysis
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.4.0'

      - name: Install StyleLint
        run: npm install -g stylelint stylelint-config-standard

      - name: Run StyleLint
        run: stylelint --config ./ci/other/.stylelintrc.json --formatter json --output stylelint-report.json "docker/frontend/css/*.css"

      # Additional Docker Analysis
      - name: Run Hadolint and generate report
        uses: hadolint/hadolint-action@v3.1.0
        with:
          config: ./ci/other/.hadolint.yaml
          dockerfile: Dockerfile
          output-file: hadolint-report.json
          recursive: true

      # Additional JavaScript Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.25.11
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.25.11

        # SonarQube Analysis (CSS, Docker, HTML, JavaScript)
      - name: Execute SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT }}
        run: |
          docker run \
          --rm \
          -e SONAR_HOST_URL="https://sonarqube.zodac.me" \
          -v "$(pwd):/usr/src/" \
          sonarsource/sonar-scanner-cli:10.0 \
            -Dsonar.projectKey=folding-stats-other  \
            -Dsonar.sources=/usr/src/docker/frontend/css/,/usr/src/docker/frontend/pages/,/usr/src/docker/frontend/js,/usr/src/docker/backend/Dockerfile,/usr/src/docker/database/Dockerfile,/usr/src/docker/frontend/Dockerfile \
            -Dsonar.token=${{ secrets.SONARQUBE_PAT }} \
            -Dsonar.docker.hadolint.reportPaths=hadolint-report.json \
            -Dsonar.css.stylelint.reportPaths=stylelint-report.json
