name: Other CI

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/other.yml'
      - 'ci/other/**'
      - 'docker/backend/Dockerfile'
      - 'docker/backend/scripts/**'
      - 'docker/database/Dockerfile'
      - 'docker/frontend/Dockerfile'
      - 'docker/frontend/css/**'
      - 'docker/frontend/js/**'
      - 'docker/frontend/pages/**'
      - 'docker/frontend/scripts/**'

jobs:
  analyze:
    name: Other Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      # Additional CSS Analysis
      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '23.3.0'

      - name: Install StyleLint
        run: npm install -g stylelint@16.11.0 stylelint-config-standard@36.0.1

      - name: Run StyleLint
        run: stylelint --config ./ci/other/.stylelintrc.json --formatter json --max-warnings 0 --output-file stylelint-report.json "docker/frontend/css/*.css" || true

      - name: Replace Stylelint directory path to match SonarQube mount path
        run: sed -i 's|/home/runner/work/folding-stats/folding-stats/docker|/usr/src/docker|g' stylelint-report.json

      # Additional Docker Analysis
      - name: Run Hadolint and generate report
        uses: hadolint/hadolint-action@v3.1.0
        with:
          config: ./ci/other/.hadolint.yaml
          dockerfile: Dockerfile
          output-file: hadolint-report.json
          recursive: true

      # Additional JavaScript Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3.26.6
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3.26.6

        # SonarQube Analysis (CSS, Docker, HTML, JavaScript)
      - name: Execute SonarQube Scan
        env:
          SONAR_HOST: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_PAT_OTHER }}
        run: |
          docker run \
          --rm \
          -e SONAR_HOST_URL=${{ vars.SONAR_HOST_URL }} \
          -v "$(pwd):/usr/src/" \
          sonarsource/sonar-scanner-cli:11.1 \
            -Dsonar.projectKey=folding-stats-other  \
            -Dsonar.projectName=folding-stats-other  \
            -Dsonar.sources=/usr/src/docker/frontend/css/,/usr/src/docker/frontend/pages/,/usr/src/docker/frontend/js,/usr/src/docker/backend/Dockerfile,/usr/src/docker/database/Dockerfile,/usr/src/docker/frontend/Dockerfile,/usr/src/docker/frontend/scripts/,/usr/src/docker/backend/scripts/ \
            -Dsonar.token=${{ secrets.SONARQUBE_PAT_OTHER }} \
            -Dsonar.docker.hadolint.reportPaths=hadolint-report.json \
            -Dsonar.css.stylelint.reportPaths=stylelint-report.json
